OPTION(WITH_NATIVE_NOTIFICATIONS "Build with native notification support" ON)

if (WITH_NATIVE_NOTIFICATIONS)
    set(KF5_MIN_VERSION "5.18.0")

    find_package(ECM ${KF5_MIN_VERSION} REQUIRED NO_MODULE)
    list(APPEND CMAKE_MODULE_PATH ${ECM_MODULE_PATH})

    if (WITH_QT6)
        set(KF6_MIN_VERSION "5.248.0")
        find_package(KF6 ${KF6_MIN_VERSION} COMPONENTS Notifications StatusNotifierItem)
        if (KF6_FOUND)
            list(APPEND copyq_LIBRARIES KF6::Notifications KF6::StatusNotifierItem)
        else()
            set(WITH_NATIVE_NOTIFICATIONS OFF CACHE BOOL "Build with native notification support" FORCE)
        endif()
    else()
        find_package(KF5 ${KF5_MIN_VERSION} COMPONENTS Notifications)
        if (KF5_FOUND)
            list(APPEND copyq_LIBRARIES KF5::Notifications)
        else()
            set(WITH_NATIVE_NOTIFICATIONS OFF CACHE BOOL "Build with native notification support" FORCE)
        endif()
    endif()

    if (WITH_NATIVE_NOTIFICATIONS)
        list(APPEND copyq_SOURCES gui/notificationnative/notificationnative.cpp)
        list(APPEND copyq_DEFINITIONS WITH_NATIVE_NOTIFICATIONS)
    endif()
endif()
